#!/bin/bash
#PBS -N qtl2_Rio
#PBS -e qtl2_Rio.err
#PBS -o qtl2_Rio.out
#PBS -l select=1:ncpus=6:mem=60gb,walltime=56:00:00
#PBS -q tillers

cd $PBS_O_WORKDIR

BASE_DIR="/zfs/tillers/panicle/lucas/projects/NAM_02-24-2020/separate_calls/data/variants/imputed/missing_filter/QTL_mapping/Beagle_imputed"
POPULATION=Rio

# module add singularity

cd ${POPULATION}
singularity run -B /zfs ~/singularity_containers/rqtl2.sif \
    Rscript ${BASE_DIR}/scan_phenotypes.R ${POPULATION}

