#!/bin/bash
#PBS -N qtl2_<LINE>
#PBS -e qtl2_<LINE>.err
#PBS -o qtl2_<LINE>.out
#PBS -l select=1:ncpus=6:mem=60gb,walltime=56:00:00
#PBS -q tillers

cd $PBS_O_WORKDIR

BASE_DIR="/panicle/lucas/projects/NAM_02-24-2020/separate_calls/data/variants/imputed/missing_filter/QTL_mapping/Beagle_imputed"
POPULATION=<LINE>

# module add singularity

cd ${POPULATION}
singularity run -B /panicle ~/singularity_containers/rqtl2.sif \
    Rscript ${BASE_DIR}/scan_phenotypes.R ${POPULATION}

